language: ruby
dist: xenial
cache: bundler

addons:
  apt:
    packages:
    - wrk
    - apache2-utils

after_success:
  - bundle exec rake benchmark:compare

matrix:
  include:
    - rvm: 2.4
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.6
      gemfile: gems/rack1.gemfile
    - rvm: 2.6
      gemfile: gems/rack3.gemfile
    - rvm: 2.6
      env: COVERAGE=BriefSummary,Coveralls
    - rvm: truffleruby
    - rvm: jruby-head
      env: JRUBY_OPTS="--debug -X+O"
    - rvm: ruby-head
  allow_failures:
    - rvm: truffleruby
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: truffleruby
    - gemfile: gems/rack3.gemfile
